### ISSUE TITLE
Questions about Featureset

### ISSUE THREAD

**Issue by solvingj** [georgeduckett/TeamCoding#2]
Is TeamCoding a real-time collaborative pair programming extension similar to VSAnywhere or AtomPair?  It looks like it might not keep the files in Sync, only show where the other person is.

**Comment by georgeduckett** [comment]
You're correct that it doesn't keep files in sync; it only shows where other people are and what docs they have open. File syncing / a shared workspace is a feature I'd like to incorporate, however realistically this won't be any time soon.
