### ISSUE TITLE
Can't toggle "show yourself" when using TeamCoding.json config

### ISSUE THREAD

**Issue by MatthewSteeples** [georgeduckett/TeamCoding#3]
### Installed product versions
- Visual Studio: 2017 Enterprise RC
- This extension: 0.8.286

### Description
When teamcoding.json is used, the option to show or not show yourself cannot be changed

### Steps to recreate
1. Create teamcoding.json
2. Open settings window

**Comment by georgeduckett** [comment]
This isn't a bug, I added the Show Self setting as a Shared Setting rather than as a User Setting.

On reflection I think doing that was a mistake; it should be a User Setting. When I have a bit of free time I'll swap it around.

**Comment by MatthewSteeples** [comment]
That's fine if it's a shared setting. It probably makes more sense there. The issue I was coming up against was that because I hadn't configured it in my json file (it's not in the example) it was keeping the value I'd set it at previously

**Comment by georgeduckett** [comment]
My bad for not including it as an example as it was a Shared Setting.

I think I will make it a User Setting, as it's main use is to confirm the sharing method is working correctly. That's generally something each user would do once (until confirming working) then turn off.

**Comment by georgeduckett** [comment]
@MatthewSteeples I've just pushed an update to the VS gallery that should sort this out; you can now choose to show your own avatar (or not) regardless of the existence of a `teamcoding.json` file.
